apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHB6YmdodXl5
  CLOUDINARY_KEY: NTYyMjM0MTc5MTc3NDI3
  CLOUDINARY_SECRET: bXRQQWc1aUdIX0FyVXhEZDVTZzlWUVRUTGZv
  MAPBOX_TOKEN: pk.eyJ1Ijoic3JhdnlhdmFuZ2FsYTIwMDEiLCJhIjoiY21zYnhmZGhrMDV6MzJ6cjExdXJyMWtoayJ9.ot1cJJjCULEEN1P9lJZMVg=
  DB_URL: bW9uZ29kYitzcnY6Ly9zcmF2eWF2YW5nYWxhMjAwMV9kYl91c2VyOmV5QnVCekZBd2pQdTZPRGhAY2x1c3RlcjAuamZtY2szay5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA===
