apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_KEY: ""
  CLOUDINARY_SECRET: ""
  MAPBOX_TOKEN: "pk.eyJ1Ijoic3JhdmRhbHdmM2RnbGhudmF1Z2FsYTIwMDEiLCJpIjoiY21zYnhmZ2hrMDV6MzJ6cjExdXJYMWtoayJ9.ot1cJJjCULEEN1P91JZMVg="
  DB_URL: "mongodb+srv://sravyavangala2001_db_user:admin123@cluster0.jfmck3k.mongodb.net/?appName=Cluster0"
