apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: "wzjnayuo"
  CLOUDINARY_KEY: "595816851849637"
  CLOUDINARY_SECRET: "XwbdtVk3LOe4YL0NFNNzCYE5jHw"
  MAPBOX_TOKEN: "pk.eyJ1Ijoic3JhdmRhbHdmM2RnbGhudmF1Z2FsYTIwMDEiLCJpIjoiY21zYnhmZ2hrMDV6MzJ6cjExdXJYMWtoayJ9.ot1cJJjCULEEN1P91JZMVg="
  DB_URL: "mongodb+srv://sravyavangala2001_db_user:y4noYSWknbgPSKGo@cluster0.jfmck3k.mongodb.net/?appName=Cluster0"
  SECRET: "thisisacompletelyrandomsessionsecretstring"
